### ISSUE TITLE
How to setup and reference library project in Android Studio

### ISSUE THREAD

**Issue by gb96** [jfmdev/aFileDialog#1]
I am having lots of trouble completing How to Use step 1. Android studio won't let me reference a "Library Project".  Was able to do it in Eclipse, but can't figure out how to set it up in Android Studio at all.  When I import the project Android Studio wants to either replace my project in the current window or create a new Android Studio project.  Either way I cannot seem to add an Android Library Project as a dependency.  Does my Android project have to be a gradle project or something?

Any chance you could please spell out the steps in more detail? Thanks!

**Comment by jfmdev** [comment]
Hi, they are several sites in which you can find detailed explanations about how to add a library project in Android Studio, such as:
- [StackOverflow - How do I add a library project to the Android Studio?](http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio)
- [Youtube | How to Add Libraries to Android Studio](https://www.youtube.com/watch?v=1MyBO9z7ojk)
- [Truiton - Android Studio | How To Add A Library Project?](http://www.truiton.com/2015/02/android-studio-add-library-project/)

**Comment by gb96** [comment]
Hi, thanks for the help!  My project does not use gradle and all the instructions I can see seem to be based around gradle.  For now I manually include your library source code within my project source tree and then manually merge the res files (mostly with no collisions, however my strings.xml needed to just have all the aFileDialog strings included in it).
Ugly hack for now, until I get around to migrating my project to gradle.
