### ISSUE TITLE
Unable to add Library in Android Studio project

### ISSUE THREAD

**Issue by fast1234** [jfmdev/aFileDialog#10]
I have created one android studio project where I want to integrate this project. But I am not able to add compile time dependency of this project in build.gradle file. like for other projects which i tried, I used following line of code:

> compile 'com.nononsenseapps:filepicker:3.1.0'

Please provide help on this

**Comment by ianni67** [comment]
Please read the answer in: http://stackoverflow.com/a/31121228/5812071
before following the provided directions, rename the "app" directory in the library to something like "afiledialog" and then always use this directory (and not the upper level "library" directory) while importing.
If you incur in an error with manifest merging, just follow the indications provided in the log. Will work flawlessly.
