### ISSUE TITLE
/storage/emulated/0 not visible

### ISSUE THREAD

**Issue by TheNetStriker** [jfmdev/aFileDialog#12]
On Android 7 the folder /storage/emulated/0 is not visible. (/storage/emulated seams to be empty) Also when going up on /storage the library only shows a black screen. Can you fix this?

**Comment by jfmdev** [comment]
On Android 6 and above, you must ask users to grant permissions for reading the files, for example:

```java
        // Check permissions (required starting Android 6).
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            // If permission is not granted, ask it.
            ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},
                    MY_PERMISSIONS_REQUEST_READ_EXTERNAL_STORAGE);
        }
```

You can get more information on https://developer.android.com/training/permissions/requesting#java

**Comment by TheNetStriker** [comment]
I've already implemented the WRITE_EXTERNAL_STORAGE permission on my app and the app also can read and write files to the external card. I can also navigate to the external storage using aFileExplorer, but I cannot navigate to the internal storage in /storage/emulated/0. But the app is able to access files from this folder, so it can't be a permission problem. I just cant navigate there using aFileExplorer. It just doesn't show the 0 folder. Any ideas what could be the problem?

**Comment by TheNetStriker** [comment]
I've also tested this with an android emulator using the latest api (28) and the folder is also not visible. The problem seams to be that only the root user can list directories in /storage/emulated. I've implemented and uploaded a workarround for this here: https://github.com/jfmdev/aFileDialog/pull/13
