### ISSUE TITLE
**Fiber version**

### ISSUE THREAD

**Issue by johnuno11** [jfmdev/aFileDialog#15]
**Fiber version**

**Issue description**

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

__Originally posted by @johnuno11 in https://github.com/gofiber/fiber/issues/905__

Repair this issue 
```suggestion

```
```suggestion

```
```suggestion

```

**Comment by jfmdev** [comment]
@johnuno11 I'm not sure what is the issue about, maybe is from another repository?

**Comment by wwei76922** [comment]
Code snippet
