### ISSUE TITLE
Buttons do not display or a title...

### ISSUE THREAD

**Issue by adanecito** [jfmdev/aFileDialog#2]
Hi,
I am trying to use your library. It functions fine when I use as a dialog but I noticed the dialog when displayed show a white title bar area with no text and the buttons do not show. When I modified the xml to not fill up the parent and set the height to say 300dp I see another white area below the area where the folders/files are displayed. There are no exceptions thrown and when I view the xml for the layout in design mode in Android Studio it looks fine. I am not using the activity just the few lines of code for the dialog.

-Tony

**Comment by adanecito** [comment]
Ok. I worked with the demo and understand better what was done and got the buttons to work but noticed what I wanted to do was not possible. I wanted a simple cancel button. Looks like the design relies on the user hitting the back arrow. I prefer the cancel or close button myself.

So close the issue.

**Comment by jfmdev** [comment]
Hi Tony,
I'm going to create an issue for add the feature of including a "Cancel" button, and with luck I'm going to implement it in the next release.
Regards

**Comment by jfmdev** [comment]
The release 1.0.6 has been published and it implements the "Cancel" button.
