### ISSUE TITLE
"/storage/emulated/" dir is empty

### ISSUE THREAD

**Issue by hiro2016** [jfmdev/aFileDialog#8]
The same in "/sdcard", "/mnt/sdcard", "data".
Files under "/etc" are visible, some kind of permissions issue?

Sorry in advance if this question has got nothing to do with your library.

**Self resolved**  
Needed:

```
<uses-permission android:name="android.permission.WRITE_OWNER_DATA"></uses-permission> 
<uses-permission android:name="android.permission.READ_OWNER_DATA"></uses-permission>`
```

**Comment by jfmdev** [comment]
Thanks for your contribution

**Comment by alexf1** [comment]
I had this same issue but I had to also go to the app permissions and enable the storage permission (Galaxy S5 MM)
